---
title: "discovery"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{discovery}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

### The {gt} Interactive Solution

The linking is hard-coded into the table.

```{r}
admiraldiscovery::interactive_discovery("gt")
```

### The {reactable} Interactive Solution

The linking is hard-coded into the table.

```{r}
admiraldiscovery::interactive_discovery("reactable")
```

### The `knitr::kable()` Static Solution

Auto-linking works here.

```{r}
admiraldiscovery::discovery |> 
  dplyr::mutate(
    fn_linked = glue::glue("`{package}::{fn}()`"),
    .before = package
  ) |> 
  dplyr::select(-c("package", "fn", "fn_url")) |> 
  knitr::kable()
```

### The {gt} Static Solution

Auto-linking works here.

```{r}
library(gt)

admiraldiscovery::discovery |> 
  dplyr::mutate(
    fn_linked = glue::glue("`{package}::{fn}()`"),
    .before = package
  ) |> 
  dplyr::select(-c("package", "fn", "fn_url")) |> 
  gt::gt() |> 
  fmt_markdown()
```
